### PR TITLE
Update Geometry.hs

### PR DESCRIPTION
**Pull request by codereport**
Right and left should be swapped. Thanks for posting this though!

https://math.stackexchange.com/questions/2121112/how-do-i-visualize-if-three-points-represent-a-right-or-left-turn

### CODE REVIEW

**Comment by Vincibean** [comment]
Good catch! Now I suppose that `clockwise` isn't a good name for the inner method anymore...

**Comment by codereport** [comment]
Yea, I just called it determinant as the is the mathematical name for it and I couldn't think of anything better.
________________________________

**Comment by Vincibean** [comment]
I was considering `anticlockwise`, but `determinant` is definitely better.
Can you change the code accordingly?

**Comment by codereport** [comment]
Yep, just updated the changes.

**Comment by Vincibean** [comment]
Thanks!

**Pull request merged**
